<?php if (!$renderedWidgets) return; // não mostrar apenas os botões, se nenhum elemento retornar widget. ?>
<form method="get" action="" class="form_search form">
    <fieldset><legend><?php echo $legend; ?></legend>
        <?php foreach ($renderedWidgets as $k => $v): ?>
            <?php echo $v; ?>
        <?php endforeach; ?>
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button>
        <a href="<?php echo $resetUrl; ?>" class="btn btn-default">Limpar</a>
    </div>
</form>
